# Site settings
title: Data Service Continuing Professional Education
email: dscpe.info@gmail.com
logo: 
description: >
 An eight-week online intensive learning experience geared toward preparing working professionals to provide needed data services.
url: "https://dspep.github.io/"

# Social links
github_username: dscpe
twitter_username: 
facebook_username: 

# Build settings
markdown: kramdown
theme: minima

# plugins
plugins:
  - jekyll-redirect-from
